all: clean B

clean :
	rm -f *.class *_results.txt;

B1 :
	javac *.java
	java -cp ../ src.B1 > B1_results.txt;

B2 :
	javac *.java
	java -cp ../ src.B2 > B2_results.txt;

B3 :
	javac *.java
	java -cp ../ src.B3 > B3_results.txt;

B4 :
	javac *.java
	java -cp ../ src.B4 > B4_results.txt;

B:
	javac *.java
	java -cp ../ src.B1 > B1_results.txt;
	java -cp ../ src.B2 > B2_results.txt;
	java -cp ../ src.B3 > B3_results.txt;
	java -cp ../ src.B4 > B4_results.txt;
